//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HealthCare_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public bool IsAppointmentActive { get; set; }
        public string ProblemDescription { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Department Department { get; set; }
    }
}
