//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HealthCare_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationInfo
    {
        public int Id { get; set; }
        public System.TimeSpan MessageTime { get; set; }
        public System.DateTime MessageDate { get; set; }
        public string MessageText { get; set; }
        public int SenderId { get; set; }
        public int RecieverId { get; set; }
        public string ConnectionId { get; set; }
    }
}
