//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HealthCare_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Departments = new HashSet<Department>();
        }
    
        public int Id { get; set; }
        public string D_Name { get; set; }
        public string D_Email { get; set; }
        public Nullable<System.DateTime> D_DateOfBirth { get; set; }
        public string D_UserName { get; set; }
        public Nullable<int> D_UserId { get; set; }
        public string ProfileImagePath { get; set; }
        public bool IsEmailVerified { get; set; }
        public string D_Phone { get; set; }
        public string D_Address { get; set; }
        public string D_Gender { get; set; }
        public string D_BloodGroup { get; set; }
        public string resetCode { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
