//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HealthCare_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientReport
    {
        public int ReportId { get; set; }
        public string ReportType { get; set; }
        public string ReportAddress { get; set; }
        public int PatientId { get; set; }
        public string ReportName { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
